#     model_name : 'bolbolzaban/gpt2-persian'
model_name : 'microsoft/DialoGPT-small'
pretrained : False

data:
    batch_size : 15
    max_len : 256
    csv_file : 'data/context.csv'
    val_frac: 0.1

model:
    n_positions : 256
    n_ctx : 256
    n_embd : 512
    n_layer : 4
    n_head: 8
    n_inner : 768

opt:
    lr : 0.00008
    max_epochs: 15
    weight_decay : 0.